using Macrocosm.Common.Bases.Items;
using Macrocosm.Content.Items.Global;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System;
using System.Collections.Generic;
using Terraria;
using Terraria.GameContent;
using Terraria.GameContent.ItemDropRules;
using Terraria.ID;

namespace Macrocosm.Common.Utils
{
    public static partial class Utility
    {
        public static GlowmaskGlobalItem Glowmask(this Item item)
        {
            return item.GetGlobalItem<GlowmaskGlobalItem>();
        }

        /// <summary>
        /// Helper method that converts the first rocket ammo found in the inventory 
        /// to the projectile ID generated by rocket ammo of a vanilla launcher 
        /// (either Grenade, Rocket or Mine)
        /// </summary>
        /// <param name="player"> The player using the picked rocket ammo </param>
        /// <param name="copyWeaponType"> The launcher type to copy </param>
        /// <returns> The projectile ID, defaults to Rocket I </returns>
        public static int GetRocketAmmoProjectileID(Player player, int copyWeaponType)
        {
            static bool TryFindingSpecificMatches(int launcher, int ammo, out int pickedProjectileId)
            {
                pickedProjectileId = 0;
                return AmmoID.Sets.SpecificLauncherAmmoProjectileMatches.TryGetValue(launcher, out Dictionary<int, int> value) && value.TryGetValue(ammo, out pickedProjectileId);
            }

            if (copyWeaponType != ItemID.GrenadeLauncher && copyWeaponType != ItemID.RocketLauncher && copyWeaponType != ItemID.ProximityMineLauncher)
                return ProjectileID.RocketI;

            Item launcher = new(copyWeaponType);
            Item ammo = player.ChooseAmmo(launcher);

            if (ammo is null)
                return 0;

            int type;

            // for mini nukes, liquid rockets
            if (TryFindingSpecificMatches(copyWeaponType, ammo.type, out int pickedProjectileId))
            {
                type = pickedProjectileId;
            }
            // for rockets I to IV
            else if (ammo.ammo == AmmoID.Rocket)
            {
                type = launcher.shoot + ammo.shoot;
            }
            else
            {
                type = ProjectileID.RocketI;
            }

            return type;

        }

        public static void AddVariationToRubblemakers(int itemType, int tileType, int tileStyle)
        {
            FlexibleTileWand.RubblePlacementSmall.AddVariation(itemType, tileType, tileStyle);
            FlexibleTileWand.RubblePlacementMedium.AddVariation(itemType, tileType, tileStyle);
            FlexibleTileWand.RubblePlacementLarge.AddVariation(itemType, tileType, tileStyle);
        }

        public static void AddVariationsToRubblemakers(int itemType, int tileType, params int[] tileStyles)
        {
            FlexibleTileWand.RubblePlacementSmall.AddVariations(itemType, tileType, tileStyles);
            FlexibleTileWand.RubblePlacementMedium.AddVariations(itemType, tileType, tileStyles);
            FlexibleTileWand.RubblePlacementLarge.AddVariations(itemType, tileType, tileStyles);
        }

        public static void AddVariationsToRubblemakers(int itemType, int tileType, Range tileStyles)
        {
            FlexibleTileWand.RubblePlacementSmall.AddVariations(itemType, tileType, tileStyles);
            FlexibleTileWand.RubblePlacementMedium.AddVariations(itemType, tileType, tileStyles);
            FlexibleTileWand.RubblePlacementLarge.AddVariations(itemType, tileType, tileStyles);
        }

        public static void DrawBossBagEffect(this Item item, SpriteBatch spriteBatch, Color colorFront, Color colorBack, float rotation, float scale)
        {
            Texture2D texture = TextureAssets.Item[item.type].Value;
            Rectangle frame = texture.Frame();

            Vector2 frameOrigin = frame.Size() / 2f;
            Vector2 offset = new Vector2(item.width / 2 - frameOrigin.X, item.height - frame.Height);
            Vector2 drawPos = item.position - Main.screenPosition + frameOrigin + offset;

            float time = Main.GlobalTimeWrappedHourly;
            float timer = item.timeSinceItemSpawned / 240f + time * 0.04f;

            time %= 4f;
            time /= 2f;

            if (time >= 1f)
                time = 2f - time;

            time = time * 0.5f + 0.5f;

            for (float i = 0f; i < 1f; i += 0.25f)
            {
                float radians = (i + timer) * MathHelper.TwoPi;
                spriteBatch.Draw(texture, drawPos + new Vector2(0f, 8f).RotatedBy(radians) * time, frame, colorFront, rotation, frameOrigin, scale, SpriteEffects.None, 0);
            }

            for (float i = 0f; i < 1f; i += 0.34f)
            {
                float radians = (i + timer) * MathHelper.TwoPi;
                spriteBatch.Draw(texture, drawPos + new Vector2(0f, 4f).RotatedBy(radians) * time, frame, colorBack, rotation, frameOrigin, scale, SpriteEffects.None, 0);
            }
        }

        public static void GetInfoText(this DropRateInfo dropRateInfo, bool locked, out string stackRange, out string dropRate)
        {
            if (dropRateInfo.stackMin != dropRateInfo.stackMax)
                stackRange = $"({dropRateInfo.stackMin}-{dropRateInfo.stackMax})";
            else if (dropRateInfo.stackMin == 1)
                stackRange = "";
            else
                stackRange = "(" + dropRateInfo.stackMin + ")";

            string originalFormat = "P";
            if (dropRateInfo.dropRate < 0.001)
                originalFormat = "P4";

            if (dropRateInfo.dropRate != 1f)
                dropRate = Terraria.Utils.PrettifyPercentDisplay(dropRateInfo.dropRate, originalFormat);
            else
                dropRate = "100%";

            if (locked)
            {
                dropRate = "???";
                stackRange = "";
            }
        }

        public static float ComputeDropRarity(this DropRateInfo dropRateInfo)
        {
            float averageStack = (dropRateInfo.stackMin + dropRateInfo.stackMax) / 2f;
            float rarity = (1f - dropRateInfo.dropRate) * (1f / (averageStack + 1f));
            return rarity;
        }

        public static bool IsTorch(int itemId) => ItemID.Sets.Torches[itemId];
        public static bool IsTorch(this Item item) => IsTorch(item.type);

        public static bool IsRubblemaker(int itemId) => itemId is ItemID.RubblemakerSmall or ItemID.RubblemakerMedium or ItemID.RubblemakerLarge;
        public static bool IsRubblemaker(this Item item) => IsRubblemaker(item.type);

        public static bool IsChest(int itemId)
        {
            if (ContentSamples.ItemsByType[itemId].ModItem is IChest)
                return true;

            switch (itemId)
            {
                case ItemID.Chest:
                case ItemID.GoldChest:
                case ItemID.FrozenChest:
                case ItemID.IvyChest:
                case ItemID.LihzahrdChest:
                case ItemID.LivingWoodChest:
                case ItemID.MushroomChest:
                case ItemID.RichMahoganyChest:
                case ItemID.DesertChest:
                case ItemID.SkywareChest:
                case ItemID.WaterChest:
                case ItemID.WebCoveredChest:
                case ItemID.GraniteChest:
                case ItemID.MarbleChest:
                case ItemID.ShadowChest:
                case ItemID.GoldenChest:
                case ItemID.CorruptionChest:
                case ItemID.CrimsonChest:
                case ItemID.HallowedChest:
                case ItemID.IceChest:
                case ItemID.JungleChest:
                case ItemID.DungeonDesertChest:
                case ItemID.GolfChest:
                case ItemID.NebulaChest:
                case ItemID.SolarChest:
                case ItemID.StardustChest:
                case ItemID.VortexChest:
                case ItemID.BoneChest:
                case ItemID.LesionChest:
                case ItemID.FleshChest:
                case ItemID.GlassChest:
                case ItemID.HoneyChest:
                case ItemID.SlimeChest:
                case ItemID.SteampunkChest:
                case ItemID.AshWoodChest:
                case ItemID.BalloonChest:
                case ItemID.BambooChest:
                case ItemID.BlueDungeonChest:
                case ItemID.BorealWoodChest:
                case ItemID.CactusChest:
                case ItemID.CrystalChest:
                case ItemID.DynastyChest:
                case ItemID.EbonwoodChest:
                case ItemID.GreenDungeonChest:
                case ItemID.MartianChest:
                case ItemID.MeteoriteChest:
                case ItemID.ObsidianChest:
                case ItemID.PalmWoodChest:
                case ItemID.PinkDungeonChest:
                case ItemID.PumpkinChest:
                case ItemID.CoralChest:
                case ItemID.ShadewoodChest:
                case ItemID.SpiderChest:
                case ItemID.SpookyChest:
                    return true;

                default:
                    return false;
            }
        }

        public static bool IsChest(this Item item) => IsChest(item.type);

    }
}
